### PR TITLE
Dry run mode: continue-on-error handling for "contract not in inputs" 

### LINKED ISSUE #691: Support dry run mode in the FuelVM
## Problem overview

The FuelVM has many rules regarding transaction validity and requirements for using specific opcodes. Each opcode that touches the contract requires this contract's existence in the transactions' inputs. Another example is the `tro` opcode that requires the existence of the `Variable` output.

All those rules make the usage harder and require dry-running transactions many times on the SDK side to fulfill all rules.

## Solution

The FuelVM may support dry run mode, in which all validity rules will not abort the execution immediately. Instead, we will keep a record of what rules are failing and provide feedback at the end of the execution with all problems.

### PR DESCRIPTION
**Pull request by Dentosal**
~~Requires #918~~

Work towards #691

Adds a way to continue vm execution after each error instead of terminating immediately. This can be used to collect multiple execution errors at once, which is useful if you don't know in advance what storage, inputs or outputs the tx is going to need access to.

Names are still subject to bikeshedding.

## Checklist
- [x] Breaking changes are clearly marked as such in the PR description and changelog
- [x] New behavior is reflected in tests
- [ ] If performance characteristic of an instruction change, update gas costs as well or make a follow-up PR for that
- [x] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [x] I have reviewed the code myself
- [x] I have created follow-up issues caused by this PR and linked them here

### CODE REVIEW

File: fuel-vm/src/interpreter/blockchain.rs [hunk 1]
```diff
@@ -977,18 +1013,29 @@ struct CodeRootCtx<'vm, S> {
     ggas: RegMut<'vm, GGAS>,
     owner: OwnershipRegisters,
     pc: RegMut<'vm, PC>,
+    verifier_state: &'vm mut OnVerifyError,
+    _phantom: PhantomData<(M, Tx, Ecal)>,
 }
 
-impl<S> CodeRootCtx<'_, S> {
+impl<M, S, Tx, Ecal, OnVerifyError> CodeRootCtx<'_, M, S, Tx, Ecal, OnVerifyError> {
```
Comment (xgreenx) [inline fuel-vm/src/interpreter/blockchain.rs:1020]: Looks like it too many generics=D

**Review by xgreenx — DISMISSED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -12,6 +12,7 @@ and this project adheres to [Semantic Versioning](http://semver.org/).
 - [896](https://github.com/FuelLabs/fuel-vm/pull/896): Expose `leaf_sum` and allow binary `MerkleTree` to be built from existing precomputed leafs.
 - [882](https://github.com/FuelLabs/fuel-vm/pull/882): Add a lot of new `GTFArgs` including generic ones that will replace old tx type specific.
 - [909](https://github.com/FuelLabs/fuel-vm/pull/909): Add the `remove_recovery_id()` to `Signature`.
+- [915](https://github.com/FuelLabs/fuel-vm/pull/915): Added support for `AttemptContinue` verifier, that collects and ignores some errors instead of terminating execution. This is mean to help with gathering tx dependencies.
```
Comment (netrome) [inline CHANGELOG.md:15]:
```suggestion
- [915](https://github.com/FuelLabs/fuel-vm/pull/915): Added support for `AttemptContinue` verifier, that collects and ignores some errors instead of terminating execution. This is meant to help with gathering tx dependencies.
```

**Review by netrome — APPROVED** [review]
Just a typo, otherwise LGTM

**Review by AurelienFT — DISMISSED** [review]

**Review by xgreenx — APPROVED** [review]

**Review by AurelienFT — APPROVED** [review]
