### PR TITLE
Fix bug in `RETD` which throws `MemoryOverflow` for buffers at the very top of RAM.

### LINKED ISSUE #228: `RETD` has off-by-one for overflow check.
If `RETD` tries to return a buffer wedged right at the top of RAM (i.e., where the heap grows down from) then it will erroneously throw a `MemoryOverflow`.

### PR DESCRIPTION
**Pull request by otrho**
Closes #228.

### CODE REVIEW

File: src/interpreter/flow.rs [hunk 1]
```diff
@@ -86,7 +86,7 @@ impl<S> Interpreter<S> {
     }
 
     pub(crate) fn ret_data(&mut self, a: Word, b: Word) -> Result<Bytes32, RuntimeError> {
-        if b > MEM_MAX_ACCESS_SIZE || a >= VM_MAX_RAM - b {
```
Comment (mohammadfawaz) [inline src/interpreter/flow.rs:89]: Wow!

**Review by vlopes11 — APPROVED** [review]
