### PR TITLE
Deserialize arrays: avoid leaking partially allocated memory when failing

### LINKED ISSUE #811: Handle error in the cases with `MaybeUninit`
During decoding arrays, we use `MaybeUninit`.  If we get an error during this process, we will have a memory leak since `MaybeUninit` doesn't call drop on internal objects.

image

### PR DESCRIPTION
**Pull request by acerone85**
Closes #811

[Short description of the changes.]

* Minor changes to the logic for deserializing arrays, using a [MaybeUninit<T>; N] instead of MaybeUninit<[T]; N>. 
* Dropping initialized values when failing and the array has been partially initialized

## Checklist
- [ ] Breaking changes are clearly marked as such in the PR description and changelog
- [ ] New behavior is reflected in tests
- [ ] If performance characteristic of an instruction change, update gas costs as well or make a follow-up PR for that
- [ ] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [ ] I have reviewed the code myself
- [ ] I have created follow-up issues caused by this PR and linked them here

### After merging, notify other teams

[Add or remove entries as needed]

- [ ] [Rust SDK](https://github.com/FuelLabs/fuels-rs/)
- [ ] [Sway compiler](https://github.com/FuelLabs/sway/)
- [ ] [Platform documentation](https://github.com/FuelLabs/devrel-requests/issues/new?assignees=&labels=new+request&projects=&template=NEW-REQUEST.yml&title=%5BRequest%5D%3A+) (for out-of-organization contributors, the person merging the PR will do this)
- [ ] Someone else?

### CODE REVIEW

File: fuel-types/src/canonical.rs [hunk 1]
```diff
@@ -430,23 +430,40 @@ impl<const N: usize, T: Deserialize> Deserialize for [T; N] {
...
+                    }
                 }
-                // SAFETY: Point to the next element after every iteration.
-                // 		 We do this N times therefore this is safe.
-                ptr = unsafe { ptr.add(1) };
             }
+            let final_ptr = &mut uninit as *mut _ as *mut [T; N];
             // SAFETY: All array elements have been initialized above.
-            let init = unsafe { uninit.assume_init() };
+            let init = unsafe { final_ptr.read() };
```
Comment (acerone85) [inline fuel-types/src/canonical.rs:465]: This is ugly, but `mem::transmute` cannot be used for arrays with generic length. 

See https://github.com/rust-lang/rust/issues/61956
(The solution advocated there also mentions calling `mem::forget(uninit)`, but I don't think in this case is necessary and apparently it causes a compilation error.

File: fuel-types/src/canonical.rs [hunk 2]
```diff
@@ -430,23 +430,40 @@ impl<const N: usize, T: Deserialize> Deserialize for [T; N] {
         } else {
             // Spec doesn't say how to deserialize arrays with unaligned
             // primitives(as `u16`, `u32`, `usize`), so unpad them.
-            let mut uninit = <MaybeUninit<[T; N]>>::uninit();
+            let mut uninit: [MaybeUninit<T>; N] =
```
Comment (Dentosal) [inline fuel-types/src/canonical.rs:433]: May I suggest this pattern instead: https://github.com/FuelLabs/fuel-vm/blob/dfab064ad084115d4d2cdd0191c28d71abe8679d/fuel-compression/src/impls.rs#L128-L154

Comment (acerone85) [reply fuel-types/src/canonical.rs:435]: Done in 741007fd1

File: fuel-compression/src/key.rs [hunk 3]
```diff
@@ -44,7 +44,7 @@ impl TryFrom<u32> for RegistryKey {
     fn try_from(value: u32) -> Result<Self, Self::Error> {
         let v = value.to_be_bytes();
         if v[0] != 0 {
-            return Err("RegistryKey must be less than 2^24");
+            return Err("RegistryKey must be less than 2^24")
```
Comment (xgreenx) [inline fuel-compression/src/key.rs:47]:
```suggestion
            return Err("RegistryKey must be less than 2^24");
```

**Review by xgreenx — APPROVED** [review]

**Review by AurelienFT — APPROVED** [review]
